# Basic Data Exploration and Cleaning using Pandas

## Submitted By
- **Name:** Arun Kumar
- **Roll Number:** 23EJDAI005
- **University:** JIET
- **Internship Domain:** Data Engineering
- **Organization:** Celebal Technologies

## Objective
The objective of this project is to learn Python basics and perform basic data exploration and cleaning using the Pandas library.

In this project, an ecommerce dataset containing product information such as product names, ratings, prices, discounts, seller information, and categories is used for data analysis and preprocessing.

The following tasks are performed in this notebook:
- Loading the CSV dataset into a Pandas DataFrame
- Exploring the dataset structure and contents
- Identifying and handling missing values
- Performing filtering and column selection operations
- Removing duplicate records
- Creating a derived column (`total_amount`)
- Saving the cleaned dataset as a new CSV file

The dataset used in this project is the Combined Ecommerce Dataset containing around 1000 product records from multiple ecommerce categories.

## Importing Required Libraries

In this section, the necessary Python libraries required for data analysis and data cleaning are imported.
- Pandas is used for data manipulation and analysis.
- NumPy is used for numerical operations.

In [69]:
import pandas as pd
import numpy as np

## Loading & Exploring the Dataset

In this section, the ecommerce dataset is loaded into a Pandas DataFrame using the `read_csv()` function.

As well as we will understand the structure of the dataset by checking:
- First and last rows
- Shape of dataset
- Column names
- Data types
- Statistical summary

In [70]:
df = pd.read_csv("Combined_dataset.csv")

# Display the first few rows of the DataFrame to understand its structure
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [71]:
# Display last 5 rows
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [72]:
# Display number of rows and columns i.e. the shape of the dataset
print("Shape of Dataset:", df.shape)

Shape of Dataset: (1000, 24)

In [73]:
# Display all column names
print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [74]:
# Display data types of columns
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [75]:
# Display dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [76]:
# Display statistical summary
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

## Handling Missing Values

In this section, missing values in the dataset are identified and handled appropriately.

The following operations are performed:
- Counting missing values in each column
- Calculating total missing values
- Filling missing numerical values using mean
- Filling missing categorical values using placeholder values
- Tracking how many values were filled

In [77]:
# Checking missing values in each column

missing_values_before = df.isnull().sum()

print("Missing Values Before Cleaning:\n")
print(missing_values_before)

Missing Values Before Cleaning:

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [78]:
# Total missing values in dataset

total_missing_before = df.isnull().sum().sum()

print("Total Missing Values Before Cleaning:", total_missing_before)

Total Missing Values Before Cleaning: 2639

### Dropping Columns with Excessive Missing Values

Some columns contain a very high number of missing values and are not important for this basic data cleaning assignment.

The following columns are removed:
- `videos`
- `what_customers_said`
- `variations`
- `seller_information`

These columns mainly contain multimedia or highly complex nested information.

In [79]:
# Columns to drop

columns_to_drop = [
    'videos',
    'what_customers_said',
    'variations',
    'seller_information'
]

# Dropping columns

df = df.drop(columns=columns_to_drop)

print("Dropped Columns:")
print(columns_to_drop)

Dropped Columns:
['videos', 'what_customers_said', 'variations', 'seller_information']

### Filling Remaining Missing Values

After removing highly incomplete columns, the remaining missing values are handled.

- Numerical values are filled using mean
- Categorical values are filled using 'Unknown'

In [80]:
# Missing values before filling

discount_missing_before = df['discount'].isnull().sum()

seller_missing_before = df['seller_name'].isnull().sum()

In [81]:
# Filling missing numerical values

df['discount'] = df['discount'].fillna(df['discount'].mean())

# Filling missing categorical values

df['seller_name'] = df['seller_name'].fillna('Unknown')

In [82]:
# Checking missing values after cleaning

remaining_missing = df.isnull().sum()

print("Remaining Missing Values:\n")
print(remaining_missing)

Remaining Missing Values:

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
seller_name               0
sizes                     0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [83]:
# Cleaning summary

print("Data Cleaning Summary\n")

print(f"Total Missing Values Before Cleaning: {total_missing_before}")

print(f"Columns Dropped: {len(columns_to_drop)}")

print(f"Discount Values Filled: {discount_missing_before}")

print(f"Seller Name Values Filled: {seller_missing_before}")

total_filled = discount_missing_before + seller_missing_before

print(f"Total Values Filled: {total_filled}")

remaining_total_missing = df.isnull().sum().sum()

print(f"Remaining Missing Values After Cleaning: {remaining_total_missing}")

Data Cleaning Summary

Total Missing Values Before Cleaning: 2639
Columns Dropped: 4
Discount Values Filled: 121
Seller Name Values Filled: 301
Total Values Filled: 422
Remaining Missing Values After Cleaning: 0

## Performing Basic Data Operations

In this section, basic data manipulation operations are performed on the dataset.

The following tasks are covered:
- Selecting specific columns
- Filtering rows based on conditions
- Displaying useful subsets of the dataset

### Selecting Important Columns

Only important columns related to product information and pricing are selected for analysis.

In [84]:
# Selecting important columns

selected_columns = df[
    [
        'title',
        'rating',
        'ratings_count',
        'final_price',
        'discount',
        'category'
    ]
]

# Display selected columns
selected_columns.head()

            title  rating  ratings_count  final_price  discount   category
0     Lino Perros     3.8             15  "₹3,995.00"      58.0  backpacks
1  Tommy Hilfiger     4.5             67  "₹2,899.00"      35.0  backpacks
2           Lavie     4.4            226  "₹2,999.00"      65.0  backpacks
3          F Gear     4.4           1052  "₹1,675.00"      52.0  backpacks
4       MYTRIDENT     4.7             12  "₹2,899.00"      17.0  bath-robe

### Filtering High Rated and Highly Discounted Products

Products with:
- rating greater than 4
- discount greater than 50%

are filtered from the dataset.

In [85]:
# Filtering products

filtered_products = df[
    (df['rating'] > 4) &
    (df['discount'] > 50)
]

# Display filtered data
filtered_products.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,seller_name,sizes,best_offer,more_offers,category
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.000000,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pink solid backpacks Non-padd...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown,"[{""size"":""S""}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.000000,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy and grey printed backpack...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown,"[{""size"":""Onesize""}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,53.503982,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Soap dispenser in glazed stone...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Finish"",""specification...","{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.000000,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: 1 king bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999,54.000000,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Dimensions: Super King bedshee...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",Unknown,"[{""size"":""Super King""}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

In [86]:
# Number of filtered products

print("Number of High Rated & Highly Discounted Products:")

print(filtered_products.shape[0])

Number of High Rated & Highly Discounted Products:
319

## Removing Duplicate Records

Duplicate records can affect data quality and analysis results.

In this section:
- Duplicate rows are identified
- Total duplicate records are counted
- Duplicate rows are removed from the dataset

In [87]:
# Counting duplicate rows

duplicate_count = df.duplicated().sum()

print("Total Duplicate Rows:", duplicate_count)

Total Duplicate Rows: 0

### Removing Duplicate Rows

Duplicate rows are removed using the `drop_duplicates()` function to improve dataset quality.

Note: Here there are no duplicates in this dataset/dataframe but there could be, for those we can use following code snippet to remove duplicates.

In [88]:
# Shape before removing duplicates

shape_before = df.shape

# Removing duplicate rows

df = df.drop_duplicates()

# Shape after removing duplicates

shape_after = df.shape

print("Shape Before Removing Duplicates:", shape_before)

print("Shape After Removing Duplicates:", shape_after)

Shape Before Removing Duplicates: (1000, 20)
Shape After Removing Duplicates: (1000, 20)

In [89]:
# Duplicate removal summary

rows_removed = shape_before[0] - shape_after[0]

print("Duplicate Removal Summary\n")

print(f"Duplicate Rows Found: {duplicate_count}")

print(f"Rows Removed: {rows_removed}")

print(f"Final Number of Rows: {shape_after[0]}")

Duplicate Removal Summary

Duplicate Rows Found: 0
Rows Removed: 0
Final Number of Rows: 1000

# Cleaning and Transforming Price Data

The `final_price` column contains currency symbols and commas, which makes it unsuitable for mathematical operations.

In this section:
- Currency symbols are removed
- Commas are removed
- The column is converted into numeric datatype
- Statistical analysis is performed on cleaned prices

In [90]:
# Checking datatype before cleaning

print("Datatype Before Cleaning:")

print(df['final_price'].dtype)

Datatype Before Cleaning:
str

## Removing Currency Symbols and Converting to Numeric Format

The `final_price` column currently contains:
- Currency symbols (`₹`)
- Commas (`,`)
- Extra quotation marks (`"`)

These characters are removed before converting the column into float datatype.

In [91]:
# Cleaning final_price column

df['final_price'] = (
    df['final_price']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.replace('"', '', regex=False)
    .str.strip()
)

# Converting to numeric datatype

df['final_price'] = pd.to_numeric(df['final_price'])

print("Price Column Cleaned Successfully")

Price Column Cleaned Successfully

In [92]:
# Checking datatype after cleaning

print("Datatype After Cleaning:")

print(df['final_price'].dtype)

Datatype After Cleaning:
float64

In [93]:
# Displaying cleaned price values

df['final_price'].head()

0    3995.0
1    2899.0
2    2999.0
3    1675.0
4    2899.0
Name: final_price, dtype: float64

## Statistical Summary of Final Price

Basic statistical analysis is performed on the cleaned `final_price` column.

In [94]:
# Statistical summary

df['final_price'].describe()

count     1000.000000
mean      1706.096000
std       1783.864472
min        199.000000
25%        649.000000
50%       1099.000000
75%       2082.250000
max      17995.000000
Name: final_price, dtype: float64

# Creating Derived Columns

The dataset does not contain a `quantity` column.

For demonstration and analysis purposes:
- A sample quantity column is created
- A new derived column `total_amount` is generated using:

`total_amount = final_price × quantity`

In [95]:
# Creating random quantity values between 1 and 5

np.random.seed(42)

df['quantity'] = np.random.randint(1, 6, size=len(df))

# Display quantity column

df[['final_price', 'quantity']].head()

   final_price  quantity
0       3995.0         4
1       2899.0         5
2       2999.0         3
3       1675.0         5
4       2899.0         5

## Creating Total Amount Column

A new column named `total_amount` is created using:

`total_amount = final_price × quantity`

In [96]:
# Creating total_amount column

df['total_amount'] = df['final_price'] * df['quantity']

# Displaying new columns

df[['final_price', 'quantity', 'total_amount']].head()

   final_price  quantity  total_amount
0       3995.0         4       15980.0
1       2899.0         5       14495.0
2       2999.0         3        8997.0
3       1675.0         5        8375.0
4       2899.0         5       14495.0

In [97]:
# Statistical summary of total amount

df['total_amount'].describe()

count     1000.000000
mean      5027.805000
std       5651.825322
min        219.000000
25%       1498.500000
50%       3196.000000
75%       6420.750000
max      53996.000000
Name: total_amount, dtype: float64

# Saving the Cleaned Dataset

After completing all preprocessing and transformation steps, the cleaned dataset is saved as a new CSV file for future analysis and usage.

In [98]:
# Saving cleaned dataset

output_file = "cleaned_dataset.csv"

df.to_csv(output_file, index=False)

print(f"Cleaned dataset saved successfully as '{output_file}'")

Cleaned dataset saved successfully as 'cleaned_dataset.csv'

# Final Project Summary

In this project, an ecommerce dataset was explored and cleaned using Python and the Pandas library. The dataset contained product-related information such as product titles, ratings, prices, discounts, seller details, and categories.

## Tasks Performed

- Imported required libraries such as:
  - `Pandas`
  - `NumPy`

- Loaded the ecommerce CSV dataset into a Pandas DataFrame using `read_csv()`.

- Explored the dataset using:
  - `head()`
  - `tail()`
  - `shape`
  - `columns`
  - `dtypes`
  - `info()`
  - `describe()`

- Identified and handled missing values in multiple columns.

- Removed unnecessary columns containing sparse and complex data.

- Performed filtering and column selection operations for better analysis.

- Checked and removed duplicate records from the dataset.

- Cleaned the `final_price` column by removing currency symbols and converting it into numeric datatype.

- Created a new `quantity` column for demonstration purposes.

- Generated a derived column:

  `total_amount = final_price × quantity`

- Saved the cleaned dataset as a new CSV file named:
  
  `cleaned_dataset.csv`

## Conclusion

This project helped in understanding the basics of:
- Data exploration
- Data preprocessing
- Data cleaning
- Data transformation using Pandas

After performing all cleaning and transformation steps, the dataset became more structured and ready for further analysis and visualization tasks.